### PR TITLE
Update 2.1.3.pantheon3

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Per https://github.com/pantheon-systems/php-apm/pull/2: Remove Pantheon customizations ('depth' variable and php7 checks to disable stacktrace operations.)

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
screen shot 2017-03-01 at 3 49 03 pm

I inserted a syntax error into index.php; the result was "no stack trace", which makes sense for this error.

**Comment by greg-1-anderson** [comment]
Adding a `require_once()` of a file that did not exist printed `Fatal error` in my browser, but did not log anything in the PHP error log on the dashboard. (?)

**Comment by greg-1-anderson** [comment]
screen shot 2017-03-01 at 4 20 13 pm

Throwing an uncaught exception is caught in the Pantheon php error log; there is still no stack trace.

I tried equivalent tests on Drupal 7 with php 5.5, and got the same results in all cases -- uncaught exception is logged w/out stack trace, missing `require_once` is not logged, etc.

So, offhand I'd say this is working as it always has. 

🚢  :shipit: 🚀  ?

**Comment by davidstrauss** [comment]
Do we have APM configured in php.ini to not do stack traces for PHP 7.x?

**Comment by greg-1-anderson** [comment]
Our php.ini configuration for APM is invariant on the php version. It is:
```
apm.slow_request_enabled="1"
apm.slow_request_duration="100"
apm.enabled="1"
apm.event_enabled="1"
apm.http_enabled="1"
apm.http_error_reporting=5
```
The file amp.ini claims the default for stack trace is:
```
; apm.store_stacktrace=On
```
I did not trace through the code to verify that, though.

**Pull request merged**
